spring:
  application:
    name: hlb-udi
  config:
    import: "optional:classpath:admin.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/odoo
    username:
    password: postgresqlpw
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          lotte:
            client-id: YOUR_LOTTE_CLIENT_ID
            client-secret: YOUR_LOTTE_CLIENT_SECRET
            authorization-grant-type: client_credentials
            scope: read,write
        provider:
          lotte:
            token-uri: https://logis.lotte.net/oauth/token # 실제 롯데택배 토큰 URL로 변경해야 합니다.

application:
  title: '@project.description@'
  version: '@project.version@'